###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        container_name: sales-redis
        networks:
            - sales

    db:
        image: 'mysql:8.0'
        container_name: sales-db
        working_dir: /var/www
        volumes:
            - '.:/var/www'
        environment:
            - MYSQL_ROOT_PASSWORD=root123
            - MYSQL_DATABASE=sales_db
            - MYSQL_USER=sales_api
            - MYSQL_PASSWORD=sales123
        ports:
            - '8002:3306'
        networks:
            - sales

    nginx:
        image: 'nginx:alpine'
        container_name: sales-nginx
        working_dir: /var/www
        volumes:
            - '.:/var/www'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        networks:
            - sales

    app:
        build:
            args:
                user: dev
                uid: 1000
            context: ./phpdocker/php-fpm/
            dockerfile: Dockerfile
        working_dir: /var/www
        image: sales
        container_name: sales-app
        volumes:
            - '.:/var/www'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - sales

    # node:
    #     image: node:18
    #     container_name: sales-node
    #     working_dir: /var/www
    #     volumes:
    #         - '.:/var/www'
    #     ports:
    #         - '5173:5173'
    #     command: ["yarn", "dev"]
    #     networks:
    #         - sales

networks:
    sales:
        driver: bridge
